'use client'

import { format } from 'date-fns'
import { ptBR } from 'date-fns/locale'
import { Download, Edit2, Plus, RefreshCw, Repeat, Trash2, Wallet } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { toast } from 'sonner'

import { ActionButton } from '@/components/ui/action-button'
import { cn } from '@/lib/utils'
import { deleteCostAction } from '@/server/actions/cost-actions'
import { useCsvExport } from '@/hooks/use-csv-export'
import { CreateCostDialog } from './create-cost-dialog'
import {
  COST_TYPE_LABELS,
  formatCurrency,
  isAutoGeneratedRecurring,
  stripRecurringMarker,
} from './types'
import type { CostRow } from './types'

type Props = {
  costs: CostRow[]
  clientId: string
}

// Mesmo grid no cabeçalho e nas linhas p/ alinhar as colunas (handoff §9.2).
const GRID =
  'grid grid-cols-[108px_110px_minmax(0,1.1fr)_minmax(0,1.6fr)_130px_110px_76px] items-center gap-3.5'

/**
 * Aba Custos — redesign Senno (Financeiro-handoff §9): contador à esquerda,
 * Exportar CSV + "Novo custo" à direita; tabela num card com pill de tipo em
 * muted, valor em `destructive` e ações Editar/Excluir por linha.
 */
export function CostsTab({ costs, clientId }: Props) {
  const router = useRouter()
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState<CostRow | undefined>()
  const [deleting, setDeleting] = useState<string | null>(null)
  const { exportCsv, loading: exportLoading } = useCsvExport()

  function openCreate() {
    setEditing(undefined)
    setDialogOpen(true)
  }

  function openEdit(cost: CostRow) {
    setEditing(cost)
    setDialogOpen(true)
  }

  async function handleDelete(id: string) {
    if (!confirm('Remover este custo?')) return
    setDeleting(id)
    await deleteCostAction(id, clientId)
    toast.success('Custo removido')
    router.refresh()
    setDeleting(null)
  }

  return (
    <div className="flex flex-col gap-4">
      {/* ---- Header da aba (handoff §9.1) ---- */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <p className="text-[13px] font-medium">
          {costs.length} {costs.length === 1 ? 'custo' : 'custos'}
        </p>
        <div className="flex flex-wrap items-center gap-[9px]">
          <button
            type="button"
            disabled={exportLoading || costs.length === 0}
            onClick={() => exportCsv({ clientId, resource: 'costs' })}
            className="inline-flex h-[38px] items-center gap-2 rounded-[9px] border border-border bg-card px-3.5 text-[13px] font-semibold text-foreground transition-colors hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Download className="h-4 w-4" aria-hidden="true" />
            Exportar CSV
          </button>
          <ActionButton onClick={openCreate}>
            <Plus aria-hidden="true" />
            Novo custo
          </ActionButton>
        </div>
      </div>

      {/* ---- Tabela (handoff §9.2) ou vazio composto ---- */}
      {costs.length === 0 ? (
        <div className="flex flex-col items-center gap-[11px] rounded-[13px] border border-dashed border-border bg-card px-6 py-[46px] text-center">
          <span className="flex h-10 w-10 items-center justify-center rounded-[11px] bg-muted text-muted-foreground">
            <Wallet className="h-5 w-5" aria-hidden="true" />
          </span>
          <div className="text-sm font-semibold">Nenhum custo registrado</div>
          <p className="-mt-1 max-w-[420px] text-[12.5px] text-muted-foreground">
            Lance custos fixos e variáveis para acompanhar o resultado do mês e alimentar a DRE.
          </p>
          <ActionButton className="mt-1.5" onClick={openCreate}>
            <Plus aria-hidden="true" />
            Adicionar custo
          </ActionButton>
        </div>
      ) : (
        <div className="overflow-x-auto rounded-[13px] border border-border bg-card shadow-card">
          <div className="min-w-[860px]">
            <div
              className={cn(
                GRID,
                'border-b border-border bg-muted/40 px-[18px] py-[11px] text-[11.5px] font-semibold uppercase tracking-[0.02em] text-muted-foreground'
              )}
            >
              <div>Data</div>
              <div>Tipo</div>
              <div>Categoria</div>
              <div>Descrição</div>
              <div>Recorrente</div>
              <div className="text-right">Valor</div>
              <div />
            </div>

            {costs.map((c) => (
              <div
                key={c.id}
                className={cn(
                  GRID,
                  'border-t border-border px-[18px] py-[13px] transition-colors hover:bg-accent/50'
                )}
              >
                <div className="text-[12.5px] tabular-nums">
                  {format(new Date(c.date), 'dd/MM/yyyy', { locale: ptBR })}
                </div>
                <div>
                  <span className="inline-flex whitespace-nowrap rounded-full bg-muted px-2.5 py-[3px] text-[11px] font-semibold leading-none text-foreground">
                    {COST_TYPE_LABELS[c.type] ?? c.type}
                  </span>
                </div>
                <div className="truncate text-[12.5px]">{c.category ?? '—'}</div>
                <div className="flex min-w-0 items-center gap-1.5">
                  {isAutoGeneratedRecurring(c.description) && (
                    <Repeat className="h-3 w-3 flex-none text-primary-text" aria-hidden="true" />
                  )}
                  <span className="truncate text-[12.5px] text-foreground">
                    {stripRecurringMarker(c.description) || '—'}
                  </span>
                </div>
                <div className="text-[12.5px] text-muted-foreground">
                  {c.isRecurring ? (
                    <span className="inline-flex items-center gap-1 whitespace-nowrap rounded-full border border-border px-2.5 py-[3px] text-[11px] font-semibold leading-none text-foreground">
                      <RefreshCw className="h-2.5 w-2.5" aria-hidden="true" />
                      Template — dia {c.recurringDay ?? '?'}
                    </span>
                  ) : isAutoGeneratedRecurring(c.description) ? (
                    <span className="inline-flex items-center gap-1 whitespace-nowrap rounded-full bg-muted px-2.5 py-[3px] text-[11px] font-semibold leading-none text-foreground">
                      <Repeat className="h-2.5 w-2.5" aria-hidden="true" />
                      Auto
                    </span>
                  ) : (
                    '—'
                  )}
                </div>
                <div className="text-right text-[13px] font-semibold tabular-nums text-destructive">
                  {formatCurrency(c.amount)}
                </div>
                <div className="flex justify-end gap-1.5">
                  <button
                    type="button"
                    title="Editar"
                    aria-label="Editar custo"
                    onClick={() => openEdit(c)}
                    className="flex h-[30px] w-[30px] items-center justify-center rounded-lg text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
                  >
                    <Edit2 className="h-3.5 w-3.5" aria-hidden="true" />
                  </button>
                  <button
                    type="button"
                    title="Excluir"
                    aria-label="Remover custo"
                    disabled={deleting === c.id}
                    onClick={() => handleDelete(c.id)}
                    className="flex h-[30px] w-[30px] items-center justify-center rounded-lg text-muted-foreground transition-colors hover:bg-destructive/[0.12] hover:text-destructive disabled:opacity-50"
                  >
                    <Trash2 className="h-3.5 w-3.5" aria-hidden="true" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <CreateCostDialog
        open={dialogOpen}
        clientId={clientId}
        cost={editing}
        onOpenChange={setDialogOpen}
        onSaved={() => router.refresh()}
      />
    </div>
  )
}
