'use client'

import { format } from 'date-fns'
import { ptBR } from 'date-fns/locale'
import { Download, Edit2, Plus, RefreshCw, Repeat, Trash2 } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { toast } from 'sonner'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { deleteCostAction } from '@/server/actions/cost-actions'
import { useCsvExport } from '@/hooks/use-csv-export'
import { CreateCostDialog } from './create-cost-dialog'
import {
  COST_TYPE_LABELS,
  formatCurrency,
  isAutoGeneratedRecurring,
  stripRecurringMarker,
} from './types'
import type { CostRow } from './types'

const TYPE_COLORS: Record<string, string> = {
  FIXED: 'bg-blue-100 text-blue-800 dark:bg-blue-950/40 dark:text-blue-200',
  VARIABLE: 'bg-muted text-muted-foreground',
  MARKETING: 'bg-purple-100 text-purple-800 dark:bg-purple-950/40 dark:text-purple-200',
  PAYROLL: 'bg-amber-100 text-amber-800 dark:bg-amber-950/40 dark:text-amber-200',
  TAX_REVENUE: 'bg-red-100 text-red-800 dark:bg-red-950/40 dark:text-red-200',
  TAX_PROFIT: 'bg-red-100 text-red-800 dark:bg-red-950/40 dark:text-red-200',
  COMMISSION: 'bg-teal-100 text-teal-800 dark:bg-teal-950/40 dark:text-teal-200',
  COMMERCIAL: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-950/40 dark:text-indigo-200',
  ADMINISTRATIVE: 'bg-slate-100 text-slate-800 dark:bg-slate-800/40 dark:text-slate-200',
  FINANCIAL_EXPENSE: 'bg-rose-100 text-rose-800 dark:bg-rose-950/40 dark:text-rose-200',
  OTHER: 'bg-muted text-muted-foreground',
}

type Props = {
  costs: CostRow[]
  clientId: string
}

export function CostsTab({ costs, clientId }: Props) {
  const router = useRouter()
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState<CostRow | undefined>()
  const [deleting, setDeleting] = useState<string | null>(null)
  const { exportCsv, loading: exportLoading } = useCsvExport()

  function openCreate() {
    setEditing(undefined)
    setDialogOpen(true)
  }

  function openEdit(cost: CostRow) {
    setEditing(cost)
    setDialogOpen(true)
  }

  async function handleDelete(id: string) {
    if (!confirm('Remover este custo?')) return
    setDeleting(id)
    await deleteCostAction(id, clientId)
    toast.success('Custo removido')
    router.refresh()
    setDeleting(null)
  }

  return (
    <>
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          {costs.length} {costs.length === 1 ? 'custo' : 'custos'}
        </p>
        <div className="flex gap-2">
          <Button
            size="sm"
            variant="outline"
            disabled={exportLoading || costs.length === 0}
            onClick={() => exportCsv({ clientId, resource: 'costs' })}
          >
            <Download className="mr-1.5 h-3.5 w-3.5" />
            Exportar CSV
          </Button>
          <Button size="sm" onClick={openCreate}>
            <Plus className="mr-2 h-4 w-4" />
            Novo custo
          </Button>
        </div>
      </div>

      {costs.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-lg border border-dashed py-16 text-center">
          <p className="text-sm font-medium text-muted-foreground">Nenhum custo registrado</p>
          <Button size="sm" className="mt-4" onClick={openCreate}>
            <Plus className="mr-2 h-4 w-4" />
            Adicionar custo
          </Button>
        </div>
      ) : (
        <div className="rounded-lg border">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b bg-muted/40">
                <th className="px-4 py-2.5 text-left font-medium">Data</th>
                <th className="px-4 py-2.5 text-left font-medium">Tipo</th>
                <th className="px-4 py-2.5 text-left font-medium">Categoria</th>
                <th className="px-4 py-2.5 text-left font-medium">Descrição</th>
                <th className="px-4 py-2.5 text-left font-medium">Recorrente</th>
                <th className="px-4 py-2.5 text-right font-medium">Valor</th>
                <th className="px-4 py-2.5" />
              </tr>
            </thead>
            <tbody>
              {costs.map((c) => (
                <tr key={c.id} className="border-b last:border-0 hover:bg-muted/20">
                  <td className="px-4 py-2.5 text-muted-foreground">
                    {format(new Date(c.date), 'dd/MM/yyyy', { locale: ptBR })}
                  </td>
                  <td className="px-4 py-2.5">
                    <span
                      className={`inline-flex rounded px-1.5 py-0.5 text-xs font-medium ${TYPE_COLORS[c.type] ?? ''}`}
                    >
                      {COST_TYPE_LABELS[c.type] ?? c.type}
                    </span>
                  </td>
                  <td className="px-4 py-2.5">{c.category ?? '—'}</td>
                  <td className="px-4 py-2.5">
                    <div className="flex items-center gap-1.5">
                      {isAutoGeneratedRecurring(c.description) && (
                        <Repeat className="h-3 w-3 shrink-0 text-blue-500" />
                      )}
                      <span>{stripRecurringMarker(c.description) || '—'}</span>
                    </div>
                  </td>
                  <td className="px-4 py-2.5">
                    {c.isRecurring ? (
                      <Badge variant="outline" className="gap-1 text-xs">
                        <RefreshCw className="h-2.5 w-2.5" />
                        Template — dia {c.recurringDay ?? '?'}
                      </Badge>
                    ) : isAutoGeneratedRecurring(c.description) ? (
                      <Badge variant="secondary" className="gap-1 text-xs">
                        <Repeat className="h-2.5 w-2.5" />
                        Auto
                      </Badge>
                    ) : (
                      '—'
                    )}
                  </td>
                  <td className="px-4 py-2.5 text-right font-medium text-red-700">
                    {formatCurrency(c.amount)}
                  </td>
                  <td className="px-4 py-2.5">
                    <div className="flex justify-end gap-1">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-muted-foreground hover:text-foreground"
                        onClick={() => openEdit(c)}
                        aria-label="Editar custo"
                      >
                        <Edit2 className="h-3.5 w-3.5" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-muted-foreground hover:text-destructive"
                        disabled={deleting === c.id}
                        onClick={() => handleDelete(c.id)}
                        aria-label="Remover custo"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <CreateCostDialog
        open={dialogOpen}
        clientId={clientId}
        cost={editing}
        onOpenChange={setDialogOpen}
        onSaved={() => router.refresh()}
      />
    </>
  )
}
