import type { CostRow } from '@/server/repositories/cost-repository'
import type { RevenueRow } from '@/server/repositories/revenue-repository'
import type { ProcedureWithStats } from '@/server/repositories/procedure-repository'
import type { ProcedureForSelect } from '@/server/repositories/procedure-repository'

export type { RevenueRow, CostRow, ProcedureWithStats, ProcedureForSelect }

export type FinancialSummary = {
  current: { revenue: number; costs: number; profit: number; margin: number; count: number }
  previous: { revenue: number; costs: number; profit: number; margin: number }
  // Bloco de CAIXA (liquidez) — derivado das parcelas: recebido no mês, total a
  // receber e o que está vencido. Convive com a receita em competência (ledger DRE).
  cash: { received: number; receivable: number; overdue: number }
}

export type ChartMonth = { month: string; revenue: number; costs: number }

export type TopProcedure = {
  procedureId: string | null
  name: string
  total: number
  count: number
}

export type TopCostCategory = {
  type: string
  category: string | null
  label: string
  total: number
  count: number
}

export const COST_TYPE_LABELS: Record<string, string> = {
  FIXED: 'Fixo',
  VARIABLE: 'Variável',
  MARKETING: 'Marketing',
  PAYROLL: 'Folha',
  TAX_REVENUE: 'Imposto s/ receita',
  TAX_PROFIT: 'Imposto s/ lucro',
  COMMISSION: 'Comissão',
  COMMERCIAL: 'Despesa comercial',
  ADMINISTRATIVE: 'Despesa administrativa',
  FINANCIAL_EXPENSE: 'Despesa financeira',
  OTHER: 'Outro',
}

export const PAYMENT_METHOD_LABELS: Record<string, string> = {
  CASH: 'Dinheiro',
  PIX: 'Pix',
  CREDIT_CARD: 'Cartão crédito',
  DEBIT_CARD: 'Cartão débito',
  BANK_TRANSFER: 'Transferência',
  OTHER: 'Outro',
}

export const PAYMENT_METHODS = Object.keys(PAYMENT_METHOD_LABELS)

// Radix Select não aceita `value=""`. Sentinelas para itens "vazio" em selects.
export const NONE_VALUE = '__none__'
export const ALL_VALUE = '__all__'

// BOM para garantir que Excel detecte UTF-8 ao abrir o CSV.
const UTF8_BOM = '\uFEFF'

export function withBom(csv: string): string {
  return UTF8_BOM + csv
}

export function formatCurrency(value: number) {
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value)
}

export function formatPercent(value: number) {
  return value.toFixed(1) + '%'
}

/** Formata YYYY-MM-DD ou Date como dd/MM/yyyy em pt-BR. */
export function formatDateBr(input: string | Date): string {
  const date = typeof input === 'string' ? new Date(input + 'T12:00:00') : input
  return new Intl.DateTimeFormat('pt-BR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  }).format(date)
}

const RECURRING_MARKER_RE = /^\[recurring:[a-z0-9]+\]/i

export function stripRecurringMarker(description: string | null | undefined): string {
  if (!description) return ''
  return description.replace(/^\[recurring:[a-z0-9]+\]\s*/i, '')
}

export function isAutoGeneratedRecurring(description: string | null | undefined): boolean {
  if (!description) return false
  return RECURRING_MARKER_RE.test(description)
}

export function extractRecurringMarker(description: string | null | undefined): string {
  if (!description) return ''
  const m = RECURRING_MARKER_RE.exec(description)
  return m ? m[0] : ''
}

function escapeCsvCell(value: unknown): string {
  const str = value === null || value === undefined ? '' : String(value)
  if (/[",;\n\r]/.test(str)) {
    return '"' + str.replace(/"/g, '""') + '"'
  }
  return str
}

export function toCsv<T extends Record<string, unknown>>(rows: T[], columns: (keyof T)[]): string {
  const header = columns.map((c) => escapeCsvCell(String(c))).join(';')
  const body = rows.map((row) => columns.map((c) => escapeCsvCell(row[c])).join(';')).join('\n')
  return header + '\n' + body
}

export function parseCsv(text: string): string[][] {
  const rows: string[][] = []
  let current: string[] = []
  let cell = ''
  let inQuotes = false
  let i = 0
  while (i < text.length) {
    const ch = text[i]
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          cell += '"'
          i += 2
          continue
        }
        inQuotes = false
        i++
        continue
      }
      cell += ch
      i++
      continue
    }
    if (ch === '"') {
      inQuotes = true
      i++
      continue
    }
    if (ch === ',' || ch === ';' || ch === '\t') {
      current.push(cell)
      cell = ''
      i++
      continue
    }
    if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++
      current.push(cell)
      rows.push(current)
      current = []
      cell = ''
      i++
      continue
    }
    cell += ch
    i++
  }
  if (cell.length > 0 || current.length > 0) {
    current.push(cell)
    rows.push(current)
  }
  return rows.filter((r) => r.some((c) => c.trim().length > 0))
}
